lv_ba:
  ros__parameters:
    cam_model:
      cam_width: 1600
      cam_height: 1296
      scale: 0.5
      cam_fx: 733.347088
      cam_fy: 733.652700
      cam_cx: 768.670454
      cam_cy: 624.177971
      cam_d0: 0.0
      cam_d1: 0.0
      cam_d2: 0.0
      cam_d3: 0.0

    extrin_calib:
      extrinsic_T: [0.0, 0.0, 0.0]
      extrinsic_R: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
      Rcl: [-0.012330, -0.999830, -0.013650,
            -0.001750,  0.013670, -0.999910,
             0.999920, -0.012310, -0.001920]
      Pcl: [0.039420, 0.015750, -0.007440]

    data_config:
      data_path: "dataset/20260307_100516/"
      colmap_db_path: "no_colmap.db"
      image_sample_step: 5
      enable_lidar_ba: true
      enable_visual_ba: true

    window_ba:
      enable: true
      size: 20
      anchor_leaf_size: 0.01
      use_window_ba_rel: true

    BALM_stage1:
      enable: true
      root_voxel_size: 1.0
      eigen_ratio_array: [0.2, 0.2, 0.2, 0.2]

    BALM_stage2:
      root_voxel_size: 0.5
      eigen_ratio_array: [0.08, 0.08, 0.08, 0.08]

    track_fusion:
      min_view_angle: 8.0
      reproj_mean_thr: 15.0

    colmap_output:
      enable: true
      filter_size_points3D: 0.01